Testing playwright
prefie/OwnChGK pull request #27
Opened 2023-11-18 09:58 UTC by udarenienao

Перетащила тесты в отдельную папку, пока оставила оба варианта - и селениум, и плейрайт. запускаются спокойно также `npm test`

2023-11-19 19:15 UTC, prefie requested changes

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +import { ADMIN_URL, LOGIN_USER_SECRET, PASSWORD_USER_SECRET, URL } from "../test-helper";
URL не используется

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +const { firefox } = require('playwright');
Давайте однообразно через import {} from?

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +let page;
Можно заимпортить Page из playwright'a и тут написать тип

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +let page;
Дополнительно я бы подумал над тем, как не использовать "глобальную переменную" page, но необязательно в этой задаче

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    const restoreLink = await page.$('#restore');
https://playwright.dev/docs/api/class-frame#deprecated
-- тут говорят, что .$ deprecated

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    await page.waitForNavigation();
https://playwright.dev/docs/api/class-frame#frame-wait-for-navigation

-> и это тоже deprecated
+ после запуска:
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================

2023-11-19 19:15 UTC, prefie commented on tests/playwright/user-ui.test.ts
> +import { LOGIN_USER_SECRET, PASSWORD_USER_SECRET, URL } from "../test-helper";
Некоторые комменты из admin-ui актуальны и тут, дублировать не буду)

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    const cookie = await page.cookies();
имхо так не работает
-> page.context().cookies()

2023-11-19 19:15 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    await page.waitForNavigation();
Этот коммент мажор, остальное минорное

2023-11-19 19:16 UTC, prefie commented
Сорре, накинул доп в виде решения конфликтов)

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/admin-ui.test.ts
> +test('Should_click_reset_for_admin', async () => {
этот тест дублируется в Should_go_to_change_password, можно его убрать

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/admin-ui.test.ts
> +    await login(LOGIN_USER_SECRET, PASSWORD_USER_SECRET, "teams");
кажется, что тут третий аргумент инородно выглядит. То есть метод называется login и логично, что в него передаем пароль и логин, а что за teams непонятно.

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/admin-ui.test.ts
> +    try {
а зачем тут try catch?

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +  expect(currentUrl).toContain('localhost');
у нас есть переменная URL можно ее заиспользовать вместо 'localhost'

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +test('Should_click_reset', async () => {
дублирует Should_go_to_change_password, можно убрать этот тест

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +async function login(email, password, elementId) {
метод повторяется и у юзера и у админа, может вынесем в helper?

2023-11-19 19:21 UTC, ShreinOlga commented on tests/ui-user.test.ts
> +import { URL } from "./test-helper";
может выкинем вообще эти тесты? Раз на playwright переходим?

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/admin-ui.test.ts
> +    await page.waitForSelector("#restoreSend");
а у playwright есть же автоматические ожидания, кажется, что не надо дополнительно перед взаимодействием с элементом проверять, что он есть в DOM, потому что это автоматически делается. https://playwright.dev/docs/actionability

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +}
будем тесты параллелить?

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +  expect(currentUrl).toContain('/team-creation');
Лучше использовать soft ассерты. Сейчас, если первая проверка упадет, то мы не узнаем, какие еще проверки не прошли. Если заиспользовать софтовые, то можно будет все результаты сразу посмотреть. https://playwright.dev/docs/best-practices#use-soft-assertions

2023-11-19 19:21 UTC, ShreinOlga commented on tests/playwright/user-ui.test.ts
> +  expect(await saveTeamButton.textContent()).toBe("Создать");
Можно воспользоваться плюшками playwright и не писать лишний код) https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text. Он еще и подождет какое-то время, прежде чем проверку сделать, выглядит удобнее

2023-11-25 07:38 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +  expect(await saveTeamButton.textContent()).toBe("Создать");
наделала

2023-11-25 07:39 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +}
хотела сделать позже, со следубщими пачками тестов

2023-11-25 07:39 UTC, udarenienao commented on tests/ui-user.test.ts
> +import { URL } from "./test-helper";
удалила

2023-11-25 07:39 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +test('Should_click_reset', async () => {
удалила

2023-11-25 07:39 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +  expect(currentUrl).toContain('localhost');
done

2023-11-25 07:39 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    await login(LOGIN_USER_SECRET, PASSWORD_USER_SECRET, "teams");
fixed

2023-11-25 07:39 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +test('Should_click_reset_for_admin', async () => {
done

2023-11-25 07:40 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    const cookie = await page.cookies();
fixed

2023-11-25 07:40 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +import { LOGIN_USER_SECRET, PASSWORD_USER_SECRET, URL } from "../test-helper";
ага

2023-11-25 07:40 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    await page.waitForNavigation();
пофиксила

2023-11-25 07:40 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    const restoreLink = await page.$('#restore');
правда, пофиксила

2023-11-25 07:41 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +let page;
в следующей задачке подумаю. пока тип явно указала

2023-11-25 07:41 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +const { firefox } = require('playwright');
done

2023-11-25 07:41 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +import { ADMIN_URL, LOGIN_USER_SECRET, PASSWORD_USER_SECRET, URL } from "../test-helper";
удалила

2023-11-25 07:41 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +async function login(email, password, elementId) {
вынесла

2023-11-25 07:44 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    await page.waitForSelector("#restoreSend");
согласна, вроде ок все, пофиксила

2023-11-25 07:52 UTC, udarenienao commented on tests/playwright/user-ui.test.ts
> +  expect(currentUrl).toContain('/team-creation');
done

2023-11-25 07:52 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    try {
хороший вопрос, натупила, не нужен

2023-11-27 07:50 UTC, prefie approved these changes

2023-12-02 10:57 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    try {
Но остался

2023-12-02 10:57 UTC, prefie commented on tests/playwright/user-ui.test.ts
> +  expect(currentUrl).toContain('/team-creation');
чот я изменения не заметил :)

2023-12-02 10:57 UTC, prefie commented on tests/playwright/admin-ui.test.ts
> +    await expect.soft(currentUrl).toContain(ADMIN_URL);
А у тебя тесты запустились?
У меня нет, потому что expect jest'овский и в нём нет soft'a

2023-12-17 11:41 UTC, udarenienao commented on tests/playwright/admin-ui.test.ts
> +    await expect.soft(currentUrl).toContain(ADMIN_URL);
и это я не запушила)) пофиксила

2024-01-14 13:37 UTC, merged