Better errors handling
prefie/OwnChGK pull request #29
Opened 2023-11-20 10:46 UTC by alex3453

2023-11-27 08:00 UTC, prefie requested changes

2023-11-27 08:00 UTC, prefie commented on app/routers/admins.router.ts
> +    const asyncHandler = require('express-async-handler')
`import { asyncHandler } from 'express-async-handler';`
наверх

2023-11-27 08:00 UTC, prefie commented on app/routers/admins.router.ts
> +        asyncHandler(adminsController.getAll.bind(adminsController))
ну в целом ок, но мне не нравится, что надо при заведении нового эндпоинта не забыть такую вещь дописать, но тут тоже самое можно сказать и про `.bind`, я на досуге подумою, что с этим можно сделать.

2023-11-27 08:00 UTC, prefie commented on app/utils/api-error.ts
> +export class APIError extends Error {
заменим всякие `.status(403)` , `.status(401)` и прочее кастомное на твою новомодную ошибку?

2023-11-27 09:06 UTC, prefie commented on app/utils/api-error.ts
> +export class APIError extends Error {
А нужно ли разделять 403, 401, 404, ещё чего, чтобы не писать в конструктор status

2023-12-02 07:01 UTC, alex3453 commented on app/routers/admins.router.ts
> +        asyncHandler(adminsController.getAll.bind(adminsController))
подумал?

2023-12-02 11:15 UTC, prefie requested changes

2023-12-02 11:15 UTC, prefie commented on app/controllers/admins.controller.ts
> +            return res.status(404).json({message: 'admin not found'});
`throw APIError('admin not found', 404)`

2023-12-02 11:15 UTC, prefie commented on app/routers/admins.router.ts
> +        asyncHandler(adminsController.getAll.bind(adminsController))
пока не придумал, давай не в этой задаче тогда

2023-12-02 11:15 UTC, prefie commented on app/routers/admins.router.ts
> +import asyncHandler = require('express-async-handler');
так го через импорт?

2023-12-02 11:15 UTC, prefie commented on app/controllers/users.controller.ts
> -            if (error.message == 'jwt must be provided') { // TODO: убрать)
Этот хак был написан, потому что метод getTokenFromRequest внутри пытается распарсить JWT токен и у него не получается => пятисотит. Но по логике этого эндпоинта, он должен возвращать 401, если токена нет => надо не просто убрать, а дописать обработку)

2023-12-02 13:28 UTC, alex3453 commented on app/routers/admins.router.ts
> +import asyncHandler = require('express-async-handler');
не дает, не получается, красным горит

2023-12-04 11:05 UTC, alex3453 commented on app/routers/admins.router.ts
> +    const asyncHandler = require('express-async-handler')
поправил

2023-12-04 11:05 UTC, AlexUran commented on app/routers/admins.router.ts
> +import asyncHandler = require('express-async-handler');
исправил

2023-12-04 11:05 UTC, alex3453 commented on app/controllers/users.controller.ts
> -            if (error.message == 'jwt must be provided') { // TODO: убрать)
добавил кастомную ошибку

2023-12-06 14:27 UTC, prefie approved these changes

2023-12-06 14:38 UTC, prefie approved these changes

2023-12-06 14:38 UTC, prefie commented on app/utils/jwt-token.ts
> +    if (cookie === undefined) {
Может ослабить условие?

2023-12-11 10:11 UTC, merged